services:
  app:
    build:
      context: .
    container_name: olatcg-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - "./:/usr/src/app:delegated"
      - "/usr/src/app/node_modules/"

networks:
  olatcg-bridge:
    name: olatcg-bridge
    external: true